# Generated by Django 4.2.4 on 2023-08-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fen", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="chess",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
