# Generated by Django 4.2.4 on 2023-09-24 16:55

import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_chess_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chess",
            name="image",
            field=models.ImageField(
                storage=api.storage.OverwriteStorage(), upload_to="chess_image"
            ),
        ),
    ]
