# Generated by Django 4.2.4 on 2023-12-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_chess_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chess",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
